### ISSUE TITLE
Redundant comparisons

### ISSUE THREAD

**Issue by thakursaurabh1998** [shrutisheoran/hello-git#1]
https://github.com/shrutisheoran/hello-git/blob/07d05b60c932120ed87f9a147aae38630a5760aa/Assignment3.java#L50

This line can be written as:
`for(int i=2;i<n;i++)`
https://github.com/shrutisheoran/hello-git/blob/07d05b60c932120ed87f9a147aae38630a5760aa/Assignment3.java#L52
And this line can be changed to:
`if(n%i==0)`

>No need to check for the same thing inside the loop if you can check that in the condition of loop only 👍 @shrutisheoran

**Comment by shrutisheoran** [comment]
Thank you Saurabh .  I did not notice it then.
