### ISSUE TITLE
Search Feature not working accordingly.

### ISSUE THREAD

**Issue by thakursaurabh1998** [shrutisheoran/hello-git#2]
https://github.com/shrutisheoran/hello-git/blob/29448df8fd7ece632fd833608ed6321bcb0f286e/assignment10/StackImplementation.java#L49

First of all the search should return the distance from top of the stack and not bottom.
And also due to the use of `Binary Search` if there are more number of similar integers in the middle of the stack then your search will not return the top most object in the stack which is required.
Each search algorithm has an appropriate use @shrutisheoran 😄
For further read click [here](https://docs.oracle.com/javase/7/docs/api/java/util/Stack.html)

**Comment by shrutisheoran** [comment]
Thankyou so much for telling that.
